"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6tiynXrmBKh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import React, { useState } from "react"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Portfolio() {
  const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  const [formData, setFormData] = useState({
    name: '',
    email: '',
    message: '',
    subject: '',
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log(formData);
    const response = await fetch('https://script.google.com/macros/s/AKfycbxMrq8tJ2aM3Gomtuer8U5Mha-a9fYgvuUnWAqVK69lkatRl_FHz7qqt0QJwdL7JQKt/exec', {
      method: 'POST',
      body: new URLSearchParams(formData),
    });

    const result = await response.text();
    console.log(result);
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header
        className="bg-primary text-primary-foreground py-4 px-6 flex justify-between items-center">
        <div className="flex-1 flex-col">
          <div className="flex flex-1 flex-row justify-between">
            <div>
              <Link href="#" className="text-2xl font-bold" prefetch={false}>
                Pooja Yadav
              </Link>
            </div>
            <div>
              <nav className="hidden md:flex gap-6">
                <Link href="#" className="hover:underline" prefetch={false}>
                  Home
                </Link>
                <Link href="#" className="hover:underline" prefetch={false}>
                  About
                </Link>
                <Link href="#" className="hover:underline" prefetch={false}>
                  Qualifications
                </Link>
                <Link href="#" className="hover:underline" prefetch={false}>
                  Projects
                </Link>
                <Link href="#" className="hover:underline" prefetch={false}>
                  Testimonials
                </Link>
                <Link href="#contact" className="hover:underline" prefetch={false}>
                  Contact
                </Link>
              </nav>
            </div>
          {/* Mobile menu button */}
          <Button variant="outline" className="md:hidden" onClick={toggleMenu}>
            <MenuIcon className="h-6 w-6" />
          </Button>
          </div>

        {/* Mobile menu */}
        {menuOpen && (
          <nav className="bg-primary text-primary-foreground p-4 rounded-lg shadow-md md:hidden">
            <Link href="#" className="block py-2 hover:underline" onClick={toggleMenu} prefetch={false}>
              Home
            </Link>
            <Link href="#" className="block py-2 hover:underline" onClick={toggleMenu} prefetch={false}>
              About
            </Link>
            <Link href="#" className="block py-2 hover:underline" onClick={toggleMenu} prefetch={false}>
              Qualifications
            </Link>
            <Link href="#" className="block py-2 hover:underline" onClick={toggleMenu} prefetch={false}>
              Projects
            </Link>
            <Link href="#" className="block py-2 hover:underline" onClick={toggleMenu} prefetch={false}>
              Testimonials
            </Link>
            <Link href="#" className="block py-2 hover:underline" onClick={toggleMenu} prefetch={false}>
              Contact
            </Link>
          </nav>
        )}
        </div>

      </header>
      <main className="flex-1">
        <section
          id="hero"
          className="bg-[url('/images/hero.jpg')] bg-cover bg-center py-24 px-6 text-center text-primary-foreground">
          <div className="max-w-3xl mx-auto space-y-6">
            <h1 className="text-4xl font-bold">Elevate Your Social Media Presence</h1>
            <p className="text-lg">
              As a seasoned social media marketer, I help businesses of all sizes create engaging content, build a loyal
              following, and drive measurable results.
            </p>
            <div className="flex justify-center gap-4">
              <Button>Get in Touch</Button>
              <Button variant="outline">View Portfolio</Button>
            </div>
          </div>
        </section>
        <section id="about" className="py-12 px-6 bg-background text-foreground">
          <div className="max-w-3xl mx-auto space-y-8">
            <div className="text-center">
              <h2 className="text-3xl font-bold">About Me</h2>
              <p className="text-muted-foreground">Learn more about my background and expertise.</p>
            </div>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <img
                  src="/images/pooja.jpeg"
                  width={400}
                  height={400}
                  alt="Pooja Yadav"
                  className="rounded-lg"
                  style={{ aspectRatio: "400/400", objectFit: "cover" }} />
              </div>
              <div className="space-y-4">
                <p>
                  Hi, I'm Pooja Yadav, a passionate social media marketer with over 5 years of experience helping
                  businesses of all sizes grow their online presence and reach their target audience.
                </p>
                <p>
                  I specialize in creating engaging content, building a loyal following, and driving measurable results
                  through strategic social media campaigns. My expertise spans across various platforms, including
                  Facebook, Instagram, Twitter, and LinkedIn.
                </p>
                <p>
                  I'm dedicated to staying up-to-date with the latest social media trends and best practices, ensuring
                  that my clients always have a competitive edge in the digital landscape.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="qualifications" className="py-12 px-6 bg-muted text-foreground">
          <div className="max-w-3xl mx-auto space-y-8">
            <div className="text-center">
              <h2 className="text-3xl font-bold">Qualifications & Certifications</h2>
              <p className="text-muted-foreground">Explore my professional achievements and credentials.</p>
            </div>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-background p-6 rounded-lg shadow-md">
                <h3 className="text-2xl font-bold mb-4">Education</h3>
                <ul className="space-y-2">
                  <li>
                    <h4 className="font-semibold">Bachelor of Marketing</h4>
                    <p className="text-muted-foreground">University of XYZ, 2017</p>
                  </li>
                  <li>
                    <h4 className="font-semibold">Social Media Marketing Certification</h4>
                    <p className="text-muted-foreground">Coursera, 2020</p>
                  </li>
                  <li>
                    <h4 className="font-semibold">Google Analytics Certification</h4>
                    <p className="text-muted-foreground">Google, 2021</p>
                  </li>
                </ul>
              </div>
              <div className="bg-background p-6 rounded-lg shadow-md">
                <h3 className="text-2xl font-bold mb-4">Experience</h3>
                <ul className="space-y-2">
                  <li>
                    <h4 className="font-semibold">Social Media Marketer</h4>
                    <p className="text-muted-foreground">ABC Agency, 2018 - 2021</p>
                  </li>
                  <li>
                    <h4 className="font-semibold">Digital Marketing Specialist</h4>
                    <p className="text-muted-foreground">XYZ Company, 2021 - Present</p>
                  </li>
                  <li>
                    <h4 className="font-semibold">Freelance Social Media Consultant</h4>
                    <p className="text-muted-foreground">2017 - Present</p>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section id="projects" className="py-12 px-6 bg-background text-foreground">
          <div className="max-w-3xl mx-auto space-y-8">
            <div className="text-center">
              <h2 className="text-3xl font-bold">My Projects</h2>
              <p className="text-muted-foreground">Explore a selection of my recent social media marketing projects.</p>
            </div>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-muted p-6 rounded-lg shadow-md">
                <img
                  src="/images/project1.jpg"
                  width={400}
                  height={300}
                  alt="Project 1"
                  className="rounded-lg mb-4"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                <h3 className="text-2xl font-bold mb-2">Project 1</h3>
                <p className="text-muted-foreground mb-4">
                  Developed a successful social media campaign for a local restaurant, resulting in a 30% increase in
                  followers and a 20% boost in online orders.
                </p>
                <Button>View Case Study</Button>
              </div>
              <div className="bg-muted p-6 rounded-lg shadow-md">
                <img
                  src="/images/project2.jpg"
                  width={400}
                  height={300}
                  alt="Project 2"
                  className="rounded-lg mb-4"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                <h3 className="text-2xl font-bold mb-2">Project 2</h3>
                <p className="text-muted-foreground mb-4">
                  Crafted a comprehensive social media strategy for a small e-commerce business, leading to a 50%
                  increase in website traffic and a 25% boost in online sales.
                </p>
                <Button>View Case Study</Button>
              </div>
            </div>
          </div>
        </section>
        <section id="testimonials" className="py-12 px-6 bg-muted text-foreground">
          <div className="max-w-3xl mx-auto space-y-8">
            <div className="text-center">
              <h2 className="text-3xl font-bold">What Clients Say</h2>
              <p className="text-muted-foreground">Hear from some of my satisfied clients.</p>
            </div>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-background p-6 rounded-lg shadow-md">
                <div className="flex items-center mb-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div className="ml-4">
                    <h4 className="font-semibold">John Doe</h4>
                    <p className="text-muted-foreground">CEO, ABC Company</p>
                  </div>
                </div>
                <p className="text-muted-foreground">
                  "Pooja's expertise in social media marketing has been\n invaluable. She helped us reach a wider
                  audience and\n significantly increase our online engagement."
                </p>
              </div>
              <div className="bg-background p-6 rounded-lg shadow-md">
                <div className="flex items-center mb-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div className="ml-4">
                    <h4 className="font-semibold">Jane Smith</h4>
                    <p className="text-muted-foreground">Marketing Manager, XYZ Corp</p>
                  </div>
                </div>
                <p className="text-muted-foreground">
                  "I've worked with Pooja on several social media campaigns, and\n she consistently delivers outstanding
                  results. Her creativity\n and strategic approach are unmatched."
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="py-12 px-6 bg-primary text-primary-foreground">
          <div className="max-w-3xl mx-auto space-y-8">
            <div className="text-center">
              <h2 className="text-3xl font-bold">Get in Touch</h2>
              <p className="text-foreground">Let's discuss how I can help elevate your social media presence.</p>
            </div>
            <form className="bg-background p-6 rounded-lg shadow-md" onSubmit={handleSubmit}>
              <div className="grid md:grid-cols-2 gap-4">
                <Input label="Name" placeholder="Enter your name" name="name" value={formData.name} onChange={handleChange} required/>
                <Input label="Email" type="email" placeholder="Enter your email" name="email" value={formData.email} onChange={handleChange} required/>
              </div>
              <div className="my-4">
                <Input label="Subject" placeholder="Enter the subject" name="subject" value={formData.subject} onChange={handleChange} required/>
              </div>
              <div className="my-4">
                <Textarea label="Message" placeholder="Enter your message" name="message" value={formData.message} onChange={handleChange} required/>
              </div>
              <Button type="submit" className="mt-4">
                Submit
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-6 px-6">
        <div className="max-w-3xl mx-auto flex justify-between items-center">
          <p>&copy; 2024 Pooja Yadav. All rights reserved.</p>
          <div className="flex gap-4">
            <Link href="#" className="hover:text-foreground" prefetch={false}>
              <TwitterIcon className="h-6 w-6" />
            </Link>
            <Link href="#" className="hover:text-foreground" prefetch={false}>
              <LinkedinIcon className="h-6 w-6" />
            </Link>
            <Link href="#" className="hover:text-foreground" prefetch={false}>
              <InstagramIcon className="h-6 w-6" />
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function LinkedinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="3" y1="12" x2="21" y2="12" />
      <line x1="3" y1="6" x2="21" y2="6" />
      <line x1="3" y1="18" x2="21" y2="18" />
    </svg>
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}
